#!/bin/zsh
#
# This lets you quickly jump into a project directory.
#
# Type:
#
#   c <tab>
#
# ...to autocomplete on all of your projects in the directories specified in
# `functions/_c`. Typically I'm using it like:
#
#    c nick<tab>/do<tab>
#
# ...to quickly jump into nickwaelkens/dotfiles, for example.
#

cd "$PROJECTS/$1"
