cask_args appdir: '/Applications'

tap 'caskroom/cask'
tap 'homebrew/bundle'

brew 'zsh'
brew 'hub'
brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'roundup'
brew 'unrar'
brew 'wget'
brew 'youtube-dl'

cask 'caffeine'
cask 'sublime-text'
cask 'spectacle'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
