cask_args appdir: '/Applications'

# tap 'caskroom/cask'
# tap 'homebrew/bundle'

tap 'homebrew/services'

brew 'zsh'
brew 'hub'
brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'roundup'
brew 'unrar'
brew 'wget'
brew 'yarn'

cask 'caffeine'
cask 'sublime-text'
cask 'spectacle'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
cask 'puush'
cask 'ngrok'
cask 'sequel-pro'
cask 'iterm2'
cask 'spotify'
cask 'sourcetree'
cask 'alfred'
cask 'phpstorm'
cask 'docker'
cask 'keka'
