cask_args appdir: '/Applications'

# Update to latest version of Homebrew
update

# Upgrade any already-installed formulae
upgrade
tap 'homebrew/services'

brew 'zsh'
brew 'zsh-autosuggestions'
brew 'hub'
brew 'ack'
brew 'coreutils'
brew 'grc'
brew 'imagemagick'
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'roundup'
brew 'unrar'
brew 'wget'

brew 'nano'
cask '1password'
cask 'dropbox'
cask 'flux'
cask 'caffeine'
cask 'sublime-text'
cask 'spectacle'
cask 'firefox'
cask 'google-chrome'
cask 'slack'
cask 'transmission'
cask 'tunnelbear'
cask 'vlc'
cask 'puush'
cask 'ngrok'
cask 'sequel-pro'
cask 'iterm2'
cask 'spotify'
cask 'sourcetree'
cask 'alfred'
cask 'phpstorm'
cask 'docker'
cask 'docker-clean'
cask 'keka'
cask 'macdown'
cask 'aerial'
cask 'whatsapp'

# Fonts
cask 'font-firacode-nerd-font'
cask 'font-lato'
cask 'font-open-sans'
cask 'font-open-sans-condensed'
cask 'font-source-code-pro'
cask 'font-source-sans-pro'
cask 'font-source-serif-pro'
cask 'font-roboto'
cask 'font-roboto-condensed'
cask 'font-roboto-mono'
